fmt:
  cargo fmt

test:
  cargo test

lint:
  cargo clippy

ok: fmt lint test
  @echo ok

build:
  cargo build --release

run:
  cargo run

install:
  ./install.sh

uninstall:
  rm -f ~/.local/bin/dlm-gtk
  rm -f ~/.local/share/applications/io.github.dlm.desktop
  @echo "Uninstalled"
